version: '3.7'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    hostname: mongodb
    command: mongod --auth --bind_ip_all
    env_file: [./config/mongodb/.env, ./config/mongodb/.env-exporter]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: unless-stopped
    networks:
      monitor-network:
        ipv4_address: 172.29.0.2

  mongodb-exporter:
    image: percona/mongodb_exporter:2.35.0
    container_name: mongodb-exporter
    command:
      - '--mongodb.uri=mongodb://exporter:password@mongodb:27017/admin?ssl=false'
    ports:
      - 9216:9216
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      monitor-network:
        ipv4_address: 172.29.0.3
  
  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - alertmanager
    networks:
      monitor-network:
        ipv4_address: 172.29.0.4

  grafana:
    image: "grafana/grafana"
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      monitor-network:
        ipv4_address: 172.29.0.5

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./config/alertmanager/:/etc/alertmanager/"
      - alertmanager-data:/data
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
    restart: unless-stopped
    networks:
      monitor-network:
        ipv4_address: 172.29.0.6
  
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: unless-stopped
    networks:
      monitor-network:
        ipv4_address: 172.29.0.7

  redis:
    image: redis:6.2.6
    container_name: redis
    env_file: ./config/redis/.env
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    restart: unless-stopped
    volumes: 
      - cache:/data
    networks:
      monitor-network:
        ipv4_address: 172.29.0.8

  redis-exporter:
    image: bitnami/redis-exporter
    container_name: redis-exporter
    command:
      - '--redis.addr=redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@172.29.0.8:6379'
    ports:
      - 9121:9121
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      monitor-network:
        ipv4_address: 172.29.0.9

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8090:8080/tcp
    networks:
      monitor-network:
        ipv4_address: 172.29.0.10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  
  blackbox-exporter:
    image: "prom/blackbox-exporter:latest"
    hostname: "blackbox"
    container_name: blackbox-exporter
    ports:
      - 9115:9115
    restart: unless-stopped
    volumes:
      - ./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml
    command:
      - '--config.file=/etc/prometheus/blackbox-exporter.yml'
    networks:
      monitor-network:
        ipv4_address: 172.29.0.11

networks:
  monitor-network:
    name: monitor-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.29.0.0/24

volumes:
  dbdata:
  prometheus:
  grafana:
  cache:
  alertmanager-data: